security:
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true # Включаем CSRF
        csrf_token_id: authenticate # Идентификатор токена
      logout:
        path: app_logout
        target: app_login

  access_control:
    # admin только для администраторов
    - { path: ^/admin, roles: ROLE_ADMIN }
    # остальной доступ
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
